modLoader = "javafml"
loaderVersion = "[38,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "memorycleanermissnotoredict"
version = "${version}"
displayName = "Memory Cleaner Miss-not Ore Dict"
authors = "MCTeamPotato, Awei, TexTrue"
description = '''
Memory Cleaner
'''
#logoFile = ""

[[dependencies.memorycleanermissnotoredict]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.memorycleanermissnotoredict]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.18.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.memorycleanermissnotoredict]]
modId = "architectury"
mandatory = true
versionRange = "[4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.memorycleanermissnotoredict]]
modId = "cloth_config"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"